# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Poetic Computation: Reader
email: taeyoon@sfpc.io
description: > # this means to ignore newlines until "baseurl:"
  Poetic Computation: Reader is an online-book by Taeyoon Choi about code as a form of poetry and aesthetic and ethical questions associated with code. The book is based on Choi’s lectures at the School for Poetic Computation, and independent school he co-founded in New York City. The first two chapters are published on September, 2017 with following chapters to be published over the year. Poetic Computation: Reader presents new possibilities of web browser to enhance accessibility.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tchoi8
github_username:  tchoi8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections: 
  chapters:
    title: Chapters
    output: true
    permalink: /chapters/:title/

defaults:
  - scope:
      path: ''
      type: chapters
    values:
      layout: chapter

