# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Poetic Computation: Reader"
email: taeyoon@sfpc.io
description: "Poetic Computation: Reader is an online-book by Taeyoon Choi that discusses code as a form of poetry and aesthetic while raising ethical questions associated with it. The book is based on Choi’s lectures at the School for Poetic Computation, an independent school he co-founded in New York City. The first two chapters will be published in September 2017, with the following chapters to be published over the year. Designed by HAWRAF, Poetic Computation: Reader presents new possibilities for enhanced accessibility and legibility in web browsers. Readers can change the design elements and format parameters to create their ideal reading experience. Poetic Computation: Reader is edited by Hannah Son and includes interviews with a select group of scholars and practitioners."
baseurl: "" # the subpath of your site, e.g. /blog
url: http://poeticcomputation.info # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tchoi8
github_username:  tchoi8
teaser: /assets/images/bookcover1.jpg

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections: 
  chapters:
    title: Chapters
    output: true
    permalink: /chapters/:title/

defaults:
  - scope:
      path: ''
      type: chapters
    values:
      layout: chapter

